### ISSUE TITLE
Error after launching the first task with gulp

### ISSUE THREAD

**Issue by Delemo** [Bloggerschmidt/Blank-Bootstrap-Edition#34]
Hello,
when launching my first gulp command to create proper buid folder, app.js and main.css files, I'm getting the following error:
`assert.js:265
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Applications/MAMP/htdocs/puyb_2018_05_28/templates/puyb/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Applications/MAMP/htdocs/puyb_2018_05_28/templates/puyb/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Applications/MAMP/htdocs/puyb_2018_05_28/templates/puyb/gulpfile.js:38:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)`

My config:
MacOS 10.12, Node 10.2.1, gulp 3.9.1, Joomla! 3.8.8 with Bl4nk 5.3

Regards

**Comment by Delemo** [comment]
Hello,
Any hint about this one?
It is far beyond my knwoledge but it seems gulp 4 has introduced some new syntax incompatible with previous 3.x version.

Regards

**Comment by Delemo** [comment]
Hello,
Well, with the last release (5.3.2) I could go all the way of the install process :)
For other people: be carefull to install all the 'stuff' as explained in the readme file (node, npm and gulp cli) AND login to your npm account (you may need to create one) before doing npm install in the template folder.
Bl4nk rocks…
Regards

**Comment by Bloggerschmidt** [comment]
Thanks for reply. For installing BL4NK there is no need to login to a npm account (I don't know until today that there is a login?). You can do it simply at the cli. :-)
